# Generated by Django 5.1 on 2024-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_validated_app', '0002_alter_member_registration_id_alter_show_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Member_Registration',
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
