# Generated by Django 2.2 on 2021-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_validated_app', '0003_auto_20210804_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='actions',
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(default='Actions', max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=45),
        ),
    ]
