# Generated by Django 2.2 on 2021-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_validated_app', '0005_auto_20210805_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
