# Generated by Django 2.2 on 2024-08-28 09:07

from django.db import migrations, models
import semi_restful_validated_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_validated_app', '0006_auto_20210805_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Release_Date', models.DateField(help_text='Enter the date of release', validators=[semi_restful_validated_app.models.no_future])),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
