# Generated by Django 2.2 on 2024-08-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_validated_app', '0007_auto_20240828_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='display_order',
        ),
    ]
